// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mundo.Api.Pesssoas.Data;

namespace Mundo.Api.Pesssoas.Migrations
{
    [DbContext(typeof(MundoApiPesssoasContext))]
    [Migration("20200924123336_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mundo.Api.Pesssoas.Domain.Pessoa.Pessoas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAniversario")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id_EstadoOrigem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_PaisOrigiem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PessoasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SobreNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PessoasId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Mundo.Api.Pesssoas.Domain.Pessoa.Pessoas", b =>
                {
                    b.HasOne("Mundo.Api.Pesssoas.Domain.Pessoa.Pessoas", null)
                        .WithMany("Amigos")
                        .HasForeignKey("PessoasId");
                });
#pragma warning restore 612, 618
        }
    }
}
